### ISSUE TITLE
Sockets not being disposed

### ISSUE THREAD

**Issue by JonCanning** [zeromq/fszmq#128]
My site (http://propertywithpotential.co.uk ) has been running with fszmq and NancyFX for ages and its been fine. Now, after an update, I'm guessing that sockets are not being disposed of properly since under load it will eventually stop with the following exception:

```Permission denied
   at fszmq.ContextModule.Socket(Context context, Int32 socketType)
   at Client.create[a](String endpoint, a timeout)
   at Nancy.TinyIoc.TinyIoCContainer.<>c__DisplayClass5`1.b__4(TinyIoCContainer c, NamedParameterOverloads o)
   at Nancy.TinyIoc.TinyIoCContainer.DelegateFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)```

This is the request socket code:
https://gist.github.com/JonCanning/a1ae68162bc85acd84ef …
disconnect is used by an IDisposable client implementation
As I said, this has been running without incident since last year but I'm wondering if that is by luck more then judgement!

fszmq 12.1.1
zmq 4.1.0.5 - I'm using paket to get it from: https://github.com/zeromq/fszmq/blob/master/lib/zeromq/WIN/x64/libzmq.dll

**Comment by pblasucci** [comment]
Hi Jon,

Sorry to hear you're having issues (and thanks for reaching out). 

So, after looking at your gist, a few things come to mind. First, I'm mostly certain `Socket.disconnect` doesn't really release any resources. Certainly it doesn't release _all_ the unmanaged resources associated with a socket. Additionally sockets are managed by their owning context. So, in practice, it's usually best to dispose of your `Context` instances (which is easy, since `Context` implements `IDisposable`). Also, though it's not required, you may choose to explicitly dispose of your `Socket` instances too (e.g. your context is going to hang around waaaay longer than you sockets) which also implement `IDisposable`. Last, if your solution is creating and destroying many many sockets, you may want to experiment with a different design (e.g. a pool of sockets whose lifetime, under normal circumstances, is much closer to that of the application lifetime). 

Hopefully, this helps. Please let me know if I can be of further assistance.

**Comment by JonCanning** [comment]
Nothing I tried worked so I reverted to version 12.1.0 and then 12.0.1 with the previous version of zmq and it's working! 

I'll see if I can come up with a failing test.

**Comment by pblasucci** [comment]
Rotten... I'm sorry it's proving difficult. 

A minimal complete repro would be great. Also, I'll hopefully have some time to investigate this further... but not until this weekend.

**Comment by JonCanning** [comment]
After some more investigation, if I create a context per request and dispose of it *properly* then it works. I can't identify what changed between versions, but the logs show that the same exception appeared with previous versions, albeit far less frequently, and this would force IIS to restart and the website would resume.
