### ISSUE TITLE
This package doesn't automatically resolve libzmq

### ISSUE THREAD

**Issue by haf** [zeromq/fszmq#132]
How about an [app.config](https://github.com/SuaveIO/suave/blob/master/src/Suave/App.config) that specifies it?

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <dllmap os="osx" dll="libzmq.dll" target="libzmq.dylib"/>
  <dllmap os="!windows,osx" dll="libzmq.dll" target="libzmq.so"/>
</configuration>
```

As `App.config` in the `fszmq` folder.

**Comment by pblasucci** [comment]
I'm not sure I fully understand the issue. When you say "this package" do you mean the generated NuGet package? If so, I'm not opposed to the idea, but it does raise some questions:

1. Does `dllmap` work at the application level? I thought it had to be defined at the library level (but I'm not 100% certain)
2.  Does NuGet automatically "do the right thing" with `app.config` files? I deliberately removed the bits in the old NuGet that rely on PowerShell, since it doesn't run anywhere but Windows.

Can you please elaborate so we can work out the best solution? Thanks.

(Also, total aside, in you're snippet the attributes are slightly inaccurate. They should read `dll="libzmq"`, since the libraries `DllImportAttribute`s also omit the file extension.)

**Comment by haf** [comment]
1. dllmap works fine when we reference the nuget Suave from applications, cross platform with libuv. Is that what you mean?
 2. Nuget just places the fszmq.dll.config file next to the dll file which is all the runtime needs to use it.

You're probably right about the naming.

**Comment by pblasucci** [comment]
This issue should be reevaluated in light of moving everything to .NET Standard and .NET Core.

**Comment by haf** [comment]
Just don't forget to run `ldconfig` after installing the binaries.
