### ISSUE TITLE
NuGet package version 12.2.1: An error occurred while retrieving package metadata

### ISSUE THREAD

**Issue by wjrogers** [zeromq/fszmq#146]
I am attempting to upgrade my projects that use fszmq to the latest version. After installing version 12.2.1, NuGet is broken for the solution. Every operation (including browsing "Installed" packages in the GUI) outputs this error:
```
An error occurred while retrieving package metadata for 'fszmq.12.2.1' from source 'C:\Work\...\packages'.
========== Finished ==========
Unable to read package from path 'fszmq.12.2.1\fszmq.12.2.1.nupkg'.
  File contains corrupted data.
```
I have already tried deleting the `packages` folder and letting Visual Studio restore it, but that didn't help.

Visual Studio 2015 Update 3, NuGet 3.4.4.1321.

**Comment by pblasucci** [comment]
Thanks for reporting this issue. I will try to reproduce it when I'm back near my development machine.

**Comment by pblasucci** [comment]
I've had a look at this now and I'm not sure the best way to proceed. I _can_ reproduce the issue. However, it only seems to be "triggered" by updating to this specific version. In other words, everything worked fine for a new project which directly adds the 12.2.1 package. Similarly, I had no troubles upgrading to a (slightly) earlier version (12.0.1). Additionally, I found no issues when using paket (as opposed to the Visual Studio Package Browser). Further, the _actually_ `fszmq.dll` seems unaffected. The reference was added and the project ran fine (despite the Visual Studio Package Browser reporting errors). 

Out of curiosity, from what version are you upgrading? And what happens if you uninstall-then-reinstall (as opposed to using the "upgrade" functionality)?

**Comment by wjrogers** [comment]
I am upgrading from 4.0.8-prerelease. I just tried uninstall-then-reinstall, but unfortunately got the same error.

**Comment by pblasucci** [comment]
So, I was able to track this down to the `.nupkg` file being corrupted on http://nuget.org's servers (i.e. _after_ the submission process). I've done a version bump (no feature changes) and put out a new release (12.2.2). Everything seems to be working correctly now. Please let me know if you have any further issues.

**Comment by wjrogers** [comment]
Thank you! The new package is working fine.
